CREATE TABLE REGISTRO(ID_REG INT,
                      NOMBRE VARCHAR2(40),
                      EMAIL VARCHAR2(40),
                      EDAD INT,
                      CONSTRAINT PK_ID_REG PRIMARY KEY (ID_REG));
                      
CREATE TABLE REGISTRO_MAYORES(ID_REGMAYOR INT,
                              NOMBRE VARCHAR2(40),
                              EMAIL VARCHAR2(40),
                              EDAD VARCHAR2(40),
                              CONSTRAINT PK_ID_REGMAYOR PRIMARY KEY (ID_REGMAYOR));
                              
CREATE TABLE REGISTRO_MENORES(ID_REGMENOR INT,
                              NOMBRE VARCHAR2(40),
                              EMAIL VARCHAR2(40),
                              EDAD VARCHAR2(40),
                              CONSTRAINT PK_ID_REGMENOR PRIMARY KEY (ID_REGMENOR));
                              
CREATE OR REPLACE TRIGGER RESPALDO_REGISTRO AFTER INSERT ON REGISTRO FOR EACH ROW
BEGIN
IF:NEW.EDAD<0 THEN

--CON ESTE IF SE NEGARA LA INSERCION DE EDADES NEGATIVAS Y SE IMPRIME CON UN DBMS
IF:NEW.EDAD>=18 THEN
DBMS.OUTPUT.PUT_LINE('ERROR');
INSERT INTO REGISTRO_MAYORES VALUES(:NEW.ID_REG, :NEW.NOMBRE, :NEW.EMAIL, :NEW.EDAD);

ELSE

INSERT INTO REGISTRO_MENORES VALUES(:NEW.ID_REG, :NEW.NOMBRE, :NEW.EMAIL, :NEW.EDAD);

-- " : " SIRVE PARA HACER REFERENCIA AL CAMPO
END IF;
END IF;
END;
/


INSERT INTO REGISTRO VALUES(1,'MAX','MAX@GMAIL.COM',20);
INSERT INTO REGISTRO VALUES(2,'MAX','MAX@GMAIL.COM',10);
INSERT INTO REGISTRO VALUES(3,'MAX','MAX@GMAIL.COM',-40);


SELECT * FROM REGISTRO;
SELECT * FROM REGISTRO_MAYORES;
SELECT * FROM REGISTRO_MENORES;
